<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>WORDPROMPT</title>
	<link rel="stylesheet" media="screen" type="text/css" href="css/wordprompt.css" />
	<!--[if IE]><meta http-equiv="imagetoolbar" content="no" /><meta http-equiv="X-UA-Compatible" content="IE=8" /><![endif]-->
</head>
<body>
	<div id="menu">
		<h1><a href="/">WORDPROMPT</h1>
		<div>
			<ul>
				<li><a href="/">HOME</a></li>
				<li><a href="/account">ACCOUNT</a></li>
                <li><a href="/about">ABOUT</a></li>
			</ul>
		</div>
	</div>
		<div id="cont"><div class="box large left">
        <div class="logo"></div>
        <div class="navigation">
            <ul>
				<li><a href="/">HOME</a></li>
                <li>/</li>
				<li><a href="/account">ACCOUNT</a></li>
                <li>/</li>
                <li><a href="/about">ABOUT</a></li>
			</ul>
        </div>
		<div class="container">
			  <?php echo $this->content; ?>
		</div> <!-- /container -->
	</div>	
</body>
</html>